inputCount = {
    # value to a key = no of arguments + 2
    "open": 3,
    "Search": 4,
    "Rename": 4,
    "Delete": 3,
    "CreateFile": 4,
    "CreateFolder": 4,
    "CopyPaste": 4,
    "CutPaste": 4,
    "ZipDirectory": 5,
    "UnzipDirectory": 4,
    "OpenBrowser": 2,
    "VolumeInc": 2,
    "VolumeDec": 2,
    "SearchInBrowser": 2,
    "CloseTab": 2,
    "OpenApplication": 2,
    "ShutDown": 2,
    "Restart": 2,
    "NumsLock": 2,
    "CapsLock": 2,
    "Screenshot": 2,
    "Mute": 2,
    "BrightnessInc": 2,
    "BrightnessDec": 2,
    "OpenNewTabInNewWindow": 2,
    "CloseTheCurrentTab": 2,
    "CloseTheApplication": 2,
    "SendMail": 8
}

instructions = {
    "open": ["Enter file path to open:", "Enter your last input:"],
    "Search": ["Enter file name (with extension) to search:", "Enter search directory path:", "Enter your last input:"],
    "Rename": ["Enter path to rename:", "Enter file new name:", "Enter your last input"],
    "Delete": ["Enter path to delete:", "Enter your last input"],
    "CreateFile": ["Enter folder path:", "Enter file name (with extension):", "Enter your last input"],
    "CreateFolder": ["Enter parent folder path:", "Enter folder name:", "Enter your last input"],
    "CopyPaste": ["Enter folder/file path to copy:", "Enter folder path to paste there:", "Enter your last input"],
    "CutPaste": ["Enter folder/file path to cut:", "Enter destination folder path to paste there:", "Enter your last input"],
    "ZipDirectory": ["Enter folder/file path to zip:", "Enter name of your output zip file (without extension):", "Enter destination folder:", "Enter your last input"],
    "UnzipDirectory": ["Enter zip file path:", "Enter destination folder path:", "Enter your last input"],
    "OpenBrowser": ["Enter your last input"],
    "VolumeInc": ["Enter your last input"],
    "VolumeDec": ["Enter your last input"],
    "SearchInBrowser": ["Enter your last input"],
    "CloseTab": ["Enter your last input"],
    "OpenApplication": ["Enter your last input"],
    "ShutDown": ["Enter your last input"],
    "Restart": ["Enter your last input"],
    "NumsLock": ["Enter your last input"],
    "CapsLock": ["Enter your last input"],
    "Screenshot": ["Enter your last input"],
    "Mute": ["Enter your last input"],
    "BrightnessInc": ["Enter your last input"],
    "BrightnessDec": ["Enter your last input"],
    "OpenNewTabInNewWindow": ["Enter your last input"],
    "CloseTheCurrentTab": ["Enter your last input"],
    "CloseTheApplication": ["Enter your last input"],
    "SendMail": ["Enter sender email", "Enter sender password", "Enter receiver email", "Enter mail subject", "Enter message body", "Enter attachement paths", "Enter your last input"]
}